name: flutter_test_runners
description: "Widget test runners for Flutter apps and packages."
version: 0.0.1
repository: https://github.com/Flutter-Bounty-Hunters/testing

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
