name: flutter_test_runners
description: "Widget test runners for Flutter apps and packages."
version: 0.0.4
repository: https://github.com/Flutter-Bounty-Hunters/testing/tree/main/packages/flutter_test_runners

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  meta: ^1.9.1
  test: any
  vm_service: any
  logging: ^1.3.0


dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
