name: Validate PR

on: [pull_request, workflow_dispatch]

jobs:
  test_flutter-test-runners_deep-links_android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter_test_runners/example_deep_links

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install Android SDK and launch emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: default
          arch: x86_64
          profile: Pixel_8_API_34
          emulator-options: "-no-snapshot -no-boot-anim -camera-back none -camera-front none"  # Emulator options (optional)
          script: |
            echo "Emulator is running"

      - name: Wait for Emulator to Start
        run: |
          adb wait-for-device
          adb shell input keyevent 82  # Unlock the emulator screen if it's locked

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Flutter App (Debug Mode)
        # Must be debug mode so we can enable Flutter Driver.
        run: flutter build apk --debug

      - name: Install App on Emulator
        run: flutter install --debug

      - name: Run deep link tests
        run: flutter test test_driver
